### ISSUE TITLE
Rosinterface_handler with raw catkin

### ISSUE THREAD

**Issue by johannes-graeter** [KIT-MRT/rosinterface_handler#2]
I use rosinterface_handler in my project https://github.com/johannes-graeter/limo/ with raw catkin (without mrt tools). When I clone all repos at once and build with catkin_make an error is raised:
ImportError: No module named rosinterface_handler.interface_generator_catkin

When I remove the rosinterface_handler package, clone it and build anew it works.

Any thoughts?

**Comment by poggenhans** [comment]
`catkin_make` does not build dependencies. You have to build them by hand, one by one. Better use `catkin build`, this is also the command used internally by the tools.

**Comment by johannes-graeter** [comment]
Thx the python-catkin-tools are really a lot better than raw catkin
